FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o app .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/app .
CMD ["./app"]

ENV LOGGING_LEVEL=info
ENV PORT=8089
ENV MONGO_URL=mongodb://localhost:27017
ENV ALLOWED_ORIGINS=http://localhost:8080,https://localhost,https://chatorbit-web-169178749730.asia-east1.run.app

EXPOSE 8089
CMD ["./app"]
