FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o app .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/app .
CMD ["./app"]

ENV LOGGING_LEVEL=info
ENV PORT=8089
ENV MONGO_URL=mongodb://localhost:27017

EXPOSE 8089
CMD ["./app"]
