FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o app .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/app .

ENV LOGGING_LEVEL=info
ENV PORT=8080
EXPOSE 8080
CMD ["./app"]